### PR TITLE
Moving the final version of the "Visualization" CWP to the central repo.

### PR DESCRIPTION
**Pull request by ric-bianchi**
"Visualization" CWP is ready for arXiV. Moving the final version to the central CWP folder.

### CODE REVIEW

**Comment by ric-bianchi** [comment]
pinging @graeme-a-stewart, @peremato, and @jouvin for info.

**Comment by ric-bianchi** [comment]
pinging @tpmccauley for info, too.

**Comment by hegner** [comment]
Thanks @ric-bianchi 
I like seeing a README.md as well in there. Which is good :-)

**Comment by ric-bianchi** [comment]
Thanks, @ric-bianchi ! :-)

**Pull request merged**
