### PR TITLE
 implement suggestions to Analysis WG paper in preparation for archive submission

### PR DESCRIPTION
**Pull request by msneubauer**

### CODE REVIEW

**Comment by msneubauer** [comment]
Final (hopefully) version of analysis WG paper before arXiv submission

**Comment by graeme-a-stewart** [comment]
Hi @msneubauer 

I had a quick look over things and it looks in good shape to me, but it's not a through proof read. Do you want me to...

- Merge it now because enough people read it already
- Leave it until I have time to read more thoroughly
- Wait until you get someone else to review it

?

Cheers

Graeme

**Comment by msneubauer** [comment]
Hi @graeme-a-stewart 

I would be ok if you just merged it because enough people read it already. Its been circulated to the Analysis WG and I received and implemented several comments. 

Having said that, if you have any time, I would welcome a thorough proof-read and before submitting and would implement your comments/corrections before sending to the archive. Outside of this, its ready to go.

**Comment by graeme-a-stewart** [comment]
Hi @msneubauer - I will merge and then take a copy of the document with me to read on the plane (I expect any comments would be minor).

**Pull request merged**
